[tools]
taplo = "latest"
uv = "latest"

[tasks.build]
description = "Build the docker image for the project"
run = "docker build -t ghcr.io/bryanwweber/kosyncserver:latest ."

[tasks.run]
description = "Run the web server"
run = "uv run python -m kosyncserver"
